// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BoxListView = (function(_super) {

    __extends(BoxListView, _super);

    function BoxListView() {
      this.render = __bind(this.render, this);
      return BoxListView.__super__.constructor.apply(this, arguments);
    }

    BoxListView.prototype.render = function() {
      var box, boxView, _i, _len, _ref;
      console.log('Rendering list box view');
      this.$el.html('');
      _ref = this.collection.models;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        box = _ref[_i];
        boxView = new BoxView({
          model: box
        });
        this.$el.append(boxView.render().el);
      }
      return this;
    };

    return BoxListView;

  })(Backbone.View);

}).call(this);
