// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.MainView = (function(_super) {

    __extends(MainView, _super);

    function MainView() {
      this.render = __bind(this.render, this);

      this.rnd = __bind(this.rnd, this);

      this.initialize = __bind(this.initialize, this);
      return MainView.__super__.constructor.apply(this, arguments);
    }

    MainView.prototype.initialize = function() {
      var a, b, dataC, diffa, diffb, end, experienceList, height, index, introList, item, start, translate1, translate2, width, _i,
        _this = this;
      this.views = [];
      width = $(window).width();
      height = $(window).height();
      console.log(width + 'x' + height);
      introList = new BoxList();
      introList.reset([
        {
          id: 'introtext',
          className: 'nicetext bluebox introtext centered well',
          data: {
            "0": "opacity:1;transform:translate(0px, " + (height / 2 - 100) + "px);",
            "1000": "opacity:0;transform:translate(0px, -200px);"
          },
          title: "Henrik Sandström",
          description: "CV 2013",
          longdescription: 'Scroll down!'
        }
      ]);
      this.views.push(new BoxListView({
        attributes: {
          'class': 'intro'
        },
        collection: introList
      }));
      translate1 = "opacity:0.2;transform:translate(0px, " + (height * 2) + "px);";
      translate2 = "opacity:1;transform:translate(0px, 0px);";
      start = 2300;
      diffa = 500;
      diffb = 1000;
      a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].map(function() {
        return _this.rnd(start, diffa, 0);
      });
      b = a.map(function(v) {
        return _this.rnd(v, diffb, 0.2);
      });
      dataC = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14].map((function(i) {
        var coll;
        coll = {};
        coll[a[i]] = translate1;
        coll[b[i]] = translate2;
        return coll;
      }));
      experienceList = new BoxList();
      experienceList.reset([
        {
          id: 'experienceheader',
          className: 'nicetext bluebox well',
          data: {
            '900': "opacity:0;transform:translate(0px, " + (height / 2 - 100) + "px);",
            '1500': "opacity:1;transform:translate(0px, " + (height / 2 - 100) + "px);",
            '2000': "opacity:1;transform:translate(0px, 0px);"
          },
          title: 'Experience'
        }, {
          id: 'wrapp',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Wrapp',
          description: 'Android Developer',
          longdescription: 'Working in the user facing team with responsibility for the Android client.'
        }, {
          id: 'sbla',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Sbla',
          description: "Founder/Consultant",
          longdescription: 'Android development company founded in late 2010 after about a year of hobby development. Sbla works on both in-house app and game development as well as projects for external customers.'
        }, {
          id: 'orc',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'ORC',
          description: "Team Lead/Client Developer",
          longdescription: 'Was team lead for the main team working with the Orc Trader. Team consisted of 5 developers of 3 testers doing agile/lean development in Kanban style.'
        }, {
          id: 'google',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Google',
          description: "Speech Data Specialist",
          longdescription: 'Helping out with one of their projects over the summer'
        }, {
          id: 'ericsson',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Ericsson',
          description: 'Thesis Work',
          longdescription: 'Developing a format for storing and handling indoor-maps.'
        }, {
          id: 'kth',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Royal Institue of Technology',
          description: 'Lab Assistant',
          longdescription: 'Many different courses helping students with\
      programming and problem solving in: Python, Java, Haskell, Prolog, OpenGL,\
      C/C++, and Syntax Analysis.'
        }, {
          id: 'pwc',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'PriceWaterHouseCoopers',
          description: 'IT-Administrator',
          longdescription: 'Worked as the leader of a group of 7 people. The main task was to upgrade computers and servers in many different locations in Sweden. I was also responsible for updating the company\'s database with the relevant information.'
        }, {
          id: 'onealyze',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Onealyze',
          description: 'Software Developer',
          longdescription: 'Worked with various programming assignments involving mainly PHP, SQL, and Javascript for companies such as TV4 (Swedish TV channel) and Husqvarna.'
        }, {
          id: 'nordvaxt',
          className: 'nicetext wrapp floatleft workbox img-rounded',
          title: 'Nordv&auml;xt Intressenter',
          description: 'Mentor',
          longdescription: 'Worked as a mentor with First Lego League. Helped children in grade 7 through 9 to build and program Lego robots. I was also a referee at the local First Lego League competition in Stockholm.'
        }
      ]);
      end = experienceList.length - 1;
      for (index = _i = 1; 1 <= end ? _i <= end : _i >= end; index = 1 <= end ? ++_i : --_i) {
        item = experienceList.at(index);
        item.set('data', dataC[index]);
      }
      return this.views.push(new BoxListView({
        attributes: {
          "class": 'experience'
        },
        collection: experienceList
      }));
    };

    MainView.prototype.rnd = function(a, b, x) {
      return parseInt(a, 10) + parseInt(b * (x + Math.random()), 10);
    };

    MainView.prototype.render = function() {
      var v, _i, _len, _ref;
      console.log('Rendering login view');
      this.$el.html('');
      _ref = this.views;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        v = _ref[_i];
        this.$el.append(v.render().el);
      }
      return this;
    };

    return MainView;

  })(Backbone.View);

}).call(this);
