// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.MainView = (function(_super) {

    __extends(MainView, _super);

    function MainView() {
      this.render = __bind(this.render, this);

      this.getDataTranslations = __bind(this.getDataTranslations, this);

      this.setRandomTranslation = __bind(this.setRandomTranslation, this);

      this.createAttributes = __bind(this.createAttributes, this);

      this.rnd = __bind(this.rnd, this);

      this.onExperienceListFetched = __bind(this.onExperienceListFetched, this);

      this.onEducationListFetched = __bind(this.onEducationListFetched, this);

      this.initialize = __bind(this.initialize, this);
      return MainView.__super__.constructor.apply(this, arguments);
    }

    MainView.prototype.initialize = function(refresh) {
      var introList,
        _this = this;
      this.refresh = refresh;
      this.views = [];
      this.width = $(window).width();
      this.height = $(window).height();
      console.log(this.width + 'x' + this.height);
      introList = new BoxList();
      introList.reset([
        {
          id: 'introtext',
          className: 'nicetext bluebox introtext centered well',
          data: {
            "0": "opacity:1;transform:translate(0px, " + (this.height / 2 - 100) + "px);",
            "1000": "opacity:0;transform:translate(0px, -200px);"
          },
          title: "Henrik Sandström",
          description: "CV 2013",
          longdescription: 'Scroll down!'
        }
      ]);
      this.views.push(new BoxListView({
        attributes: this.createAttributes('intro', 0, 1000),
        collection: introList
      }));
      this.experienceList = new BoxList();
      this.experienceList.setUrl('http://henriksandstromcv.appspot.com/experience');
      this.experienceList.fetch({
        success: function() {
          return _this.onExperienceListFetched();
        }
      });
      this.educationList = new BoxList();
      this.educationList.setUrl('http://henriksandstromcv.appspot.com/education');
      return this.educationList.fetch({
        success: function() {
          return _this.onEducationListFetched();
        }
      });
    };

    MainView.prototype.onEducationListFetched = function() {
      console.log('onEducationListFetched');
      console.log(this.educationList);
      this.educationList.add({
        id: 'educationheader',
        className: 'nicetext bluebox well',
        data: {
          '4300': "opacity:0;transform:translate(" + this.width + "px, 0px);",
          '5300': "opacity:1;transform:translate(0px, 0px);"
        },
        title: 'Education'
      }, {
        at: 0
      });
      this.setRandomTranslation(this.educationList, 5300, 500, 1000);
      this.views.push(new BoxListView({
        attributes: this.createAttributes('education', 4300, 8000),
        collection: this.educationList
      }));
      return this.render();
    };

    MainView.prototype.onExperienceListFetched = function() {
      console.log('onExperienceListFetched');
      console.log(this.experienceList);
      this.experienceList.add({
        id: 'experienceheader',
        className: 'nicetext bluebox well',
        data: {
          '900': "opacity:0;transform:translate(0px, " + (this.height / 2 - 100) + "px);",
          '1500': "opacity:1;transform:translate(0px, " + (this.height / 2 - 100) + "px);",
          '2000': "opacity:1;transform:translate(0px, 0px);",
          '4200': "opacity:1;transform:translate(0px, 0px);",
          '5200': "opacity:1;transform:translate(" + -this.width + "px, 0px);"
        },
        title: 'Experience'
      }, {
        at: 0
      });
      this.setRandomTranslation(this.experienceList, 2300, 500, 1000);
      this.views.push(new BoxListView({
        attributes: this.createAttributes('experience', 900, 5300),
        collection: this.experienceList
      }));
      return this.render();
    };

    MainView.prototype.rnd = function(a, b, x) {
      return parseInt(a, 10) + parseInt(b * (x + Math.random()), 10);
    };

    MainView.prototype.createAttributes = function(className, entry, exit) {
      var attr, translateGone, translateVisible;
      attr = {};
      translateGone = "opacity:0;transform:translate(" + this.width + "px, 0px);";
      translateVisible = "opacity:1;transform:translate(0px, 0px);";
      attr['class'] = className;
      attr['data-' + (entry - 1)] = translateGone;
      attr['data-' + entry] = translateVisible;
      attr['data-' + (exit - 1)] = translateVisible;
      attr['data-' + exit] = translateGone;
      return attr;
    };

    MainView.prototype.setRandomTranslation = function(list, start, diffa, diffb) {
      var dataC, end, index, item, _i, _results;
      dataC = this.getDataTranslations(start, diffa, diffb);
      end = list.length - 1;
      _results = [];
      for (index = _i = 1; 1 <= end ? _i <= end : _i >= end; index = 1 <= end ? ++_i : --_i) {
        item = list.at(index);
        _results.push(item.set('data', dataC[index]));
      }
      return _results;
    };

    MainView.prototype.getDataTranslations = function(start, diffa, diffb) {
      var a, b, dataC, translate1, translate2, translate3, translate4,
        _this = this;
      translate1 = "opacity:0.2;transform:translate(0px, " + (this.height * 2) + "px);";
      translate2 = "opacity:1;transform:translate(0px, 0px);";
      translate3 = "opacity:1;transform:translate(0px, 0px);";
      translate4 = "opacity:0;transform:translate(0px, 0px);";
      a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].map(function() {
        return _this.rnd(start, diffa, 0);
      });
      b = a.map(function(v) {
        return _this.rnd(v, diffb, 0.2);
      });
      dataC = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14].map((function(i) {
        var coll;
        coll = {};
        coll[a[i]] = translate1;
        coll[b[i]] = translate2;
        coll[start + diffa + diffb] = translate3;
        coll[start + 2 * diffa + diffb] = translate4;
        return coll;
      }));
      return dataC;
    };

    MainView.prototype.render = function() {
      var v, _i, _len, _ref;
      console.log('Rendering login view');
      this.$el.html('');
      _ref = this.views;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        v = _ref[_i];
        this.$el.append(v.render().el);
      }
      this.refresh();
      return this;
    };

    return MainView;

  })(Backbone.View);

}).call(this);
