// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.items = [$('#introtext'), $('#part1text')];

  window.onload = function() {
    _this.setSizeVariables();
    _this.centerItems();
    _this.addBubbles();
    return skrollr.init({
      forceHeight: false
    });
  };

  window.onresize = function() {
    _this.setSizeVariables();
    return _this.centerItems();
  };

  this.setSizeVariables = function() {
    _this.height = $(window).height();
    return _this.width = $(window).width();
  };

  this.centerItems = function() {
    var item, _i, _len, _ref, _results;
    _ref = _this.items;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      _results.push(item.css({
        'margin-top': _this.height / 2 - item.height() / 2
      }));
    }
    return _results;
  };

  this.addBubbles = function() {
    _this.z = d3.scale.category20c();
    _this.i = 0;
    _this.svg = d3.select("#intro").append("svg:svg").attr("width", "100%").attr("height", "100%").attr("position", "absolute");
    return setInterval((function() {
      return _this.addBubble();
    }), 300);
  };

  this.addBubble = function() {
    var x, y;
    x = Math.random() * _this.width;
    y = Math.random() * _this.height;
    return _this.svg.append("svg:circle").attr("cx", x).attr("cy", y + 100).attr("r", 1e-6).style("stroke", "lightblue").style("stroke-opacity", 1).style("fill", "lightblue").style("stroke-width", "2px").transition().duration(5000).ease('linear').attr("r", 50).style("stroke-opacity", 1e-6).attr("cy", y - 200).remove();
  };

}).call(this);
