// Generated by CoffeeScript 1.4.0
(function() {
  var Router, i, loadScript, recInclude, startApp, startIfReady,
    _this = this;

  Router = Backbone.Router.extend({
    routes: {
      '': 'cv'
    },
    cv: function() {
      var view;
      console.log('Loading Main view');
      view = new MainView(_this.skrollrObject);
      $('#skrollr-body').html(view.render().el);
      return _this.skrollrObject.refresh();
    }
  });

  loadScript = function(url, callback) {
    var head, script;
    head = document.getElementsByTagName('head')[0];
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = url;
    script.onreadystatechange = callback;
    script.onload = callback;
    return head.appendChild(script);
  };

  this.includes = ['views/box_view.js', 'views/box_list_view.js', 'views/main_view.js', 'models/box.js', 'models/box_list.js'];

  this.includesCounter = this.includes.length;

  this.documentDone = false;

  i = 0;

  recInclude = function() {
    var item;
    if (i < _this.includes.length) {
      item = _this.includes[i++];
      console.log('including: ' + item);
      return loadScript('javascripts/' + item, function() {
        _this.includesCounter--;
        console.log('Checking if ready: ' + _this.includesCounter);
        if (_this.includesCounter === 0) {
          startIfReady();
        }
        return recInclude();
      });
    }
  };

  recInclude();

  startApp = function() {
    _this.skrollrObject = skrollr.init({
      forceHeight: false
    });
    new Router();
    Backbone.history.start();
    return $('.workbox').popover({
      trigger: 'hover',
      animation: true,
      placement: 'bottom'
    });
  };

  $(function() {
    _this.documentDone = true;
    return startIfReady();
  });

  startIfReady = function() {
    console.log("start if ready: " + _this.documentDone + ", " + _this.includeCounter);
    if (_this.documentDone && _this.includesCounter === 0) {
      return startApp();
    }
  };

}).call(this);
