// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BoxList = (function(_super) {

    __extends(BoxList, _super);

    function BoxList() {
      this.setUrl = __bind(this.setUrl, this);
      return BoxList.__super__.constructor.apply(this, arguments);
    }

    BoxList.prototype.model = Box;

    BoxList.prototype.setUrl = function(url) {
      return this.url = url;
    };

    return BoxList;

  })(Backbone.Collection);

}).call(this);
